# Generated by Django 4.2.10 on 2024-02-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование валюты')),
                ('charcode', models.CharField(max_length=3, verbose_name='Код валюты')),
                ('date', models.DateField(verbose_name='Дата курса')),
                ('rate', models.FloatField(verbose_name='Курс')),
            ],
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('charcode', 'date'), name='unique_date_charcode'),
        ),
    ]
